require 'hoe'
require './lib/ordgen/version.rb'

Hoe.spec 'ordgen' do

  self.version = Pixelart::Module::Ordgen::VERSION


  self.summary = "ordgen - ordinals (generative ORC-721) inscription (on bitcoin & co) helpers to generate (pixel art) images and much more; bonus - incl. the og command-line tool"
  self.description = summary

  self.urls    = { home: 'https://github.com/ordbase/generative-orc-721' }

  self.author  = 'Gerald Bauer'
  self.email   = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['pixelart'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }
end
