require 'hoe'
require './lib/ordlite/version.rb'

Hoe.spec 'ordlite' do

  self.version =  Ordlite::VERSION


  self.summary = "ordlite - ordinals inscription (on bitcoin & co) database let's you query via sql and more"
  self.description = summary

  self.urls    = { home: 'https://github.com/ordbase/generative-orc-721' }

  self.author  = 'Gerald Bauer'
  self.email   = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['activerecord'],
    ['activerecord-utils'],
    ['logutils'],
    ['logutils-activerecord'],
    ['props'],
    ['props-activerecord'],
    ['sqlite3'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }
end
